### ISSUE TITLE
Lambda function name length limit of 64 chars can be easily hit due to this

### ISSUE THREAD

**Issue by milin82** [rearc-data/covid-19-world-cases-deaths-testing#1]
https://github.com/rearc/aws-data-exchange-covid-19-world-cases-deaths-testing/blob/f3d3a7e6dffbbdeb6c10cedb264380beb4dc957c/pre-processing/pre-processing-cfn.yaml#L52

**Comment by derekwolpert** [comment]
Added character count validation to the mast branch version of the `init.sh` file in. the demo ADX repo. This should help avoid issued caused by unintentionally going over the character limit when setting up a product.
